### ISSUE TITLE
Installation Error with Release v.1.0.10 in Terraform Script

### ISSUE THREAD

**Issue by DavidVidalCastillo** [Azure/aihub#36]
When executing the install.ps1, it is throwing this installation error. It seems that the release v.1.0.10 does not have the latest changes or we are making some mistake in the installation. Any idea where the problem might be?

![image](https://github.com/Azure/aihub/assets/11247763/b3fd2832-897f-4767-9c59-e9775750d652)

**Comment by cmendible** [comment]
Please try v1.0.11 and let me know how it goes

**Comment by DavidVidalCastillo** [comment]
We have tested version 1.0.11 and now we only receive two errors, they are the same ones we had before linked to the Graph token by an unrecognized parameter. Thanks for the effort.
![image](https://github.com/Azure/aihub/assets/11247763/ec8309c6-30e0-4254-a866-2d2d2c14b027)

**Comment by cmendible** [comment]
What version of terraform are you using? And how are you authenticating to Azure?

**Comment by DavidVidalCastillo** [comment]
We are using 1.7.4 terraform version, the .ps1 deploy this version.
![image](https://github.com/Azure/aihub/assets/11247763/a537ae0c-cd68-4d52-80a1-1bcc3ae1cc67)

previously we are login against our development Azure account using AZ CLI, this account use MFA so we are using AZ Logn --tenant... We dont see nothing strange...

**Comment by rliberoff** [comment]
It looks like this issue is caused by an outdated version of AZ CLI. Updating the AZ CLI to its latest version (2.60) fixed the issue.

Now two new issues have happened to @DavidVidalCastillo:

1. Explicit and manual acceptance of the «Responsible AI» terms to deploy Cognitive Services.

![image](https://github.com/Azure/aihub/assets/5644891/4cd809bf-7114-4b6f-9f6d-7cbfc6a08fdc)

2. An issue that seems to be related to privileges in Microsoft Entra ID to create App Registrations:

![image](https://github.com/Azure/aihub/assets/5644891/2a144a38-45d8-4eec-b791-09897b958785)

---

The proposed solution is to update the deployment documentation to include these aspects as prerequisites. I'll do that.
